//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quality.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quality.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Process.
        /// </summary>
        public static string AdditionalProcesses {
            get {
                return ResourceManager.GetString("AdditionalProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Functions.
        /// </summary>
        public static string AdminFunctions {
            get {
                return ResourceManager.GetString("AdminFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM/PM.
        /// </summary>
        public static string AMPM {
            get {
                return ResourceManager.GetString("AMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal Quality Application.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSEMBLY WO#.
        /// </summary>
        public static string AssemblyWONumber {
            get {
                return ResourceManager.GetString("AssemblyWONumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate.
        /// </summary>
        public static string BarCodeNumber {
            get {
                return ResourceManager.GetString("BarCodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Travel Card Please Wait.......
        /// </summary>
        public static string BuildingCardPleaseWait {
            get {
                return ResourceManager.GetString("BuildingCardPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel/Close.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristic.
        /// </summary>
        public static string Characteristic {
            get {
                return ResourceManager.GetString("Characteristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Hide.
        /// </summary>
        public static string ClickToHide {
            get {
                return ResourceManager.GetString("ClickToHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COIL.
        /// </summary>
        public static string Coil {
            get {
                return ResourceManager.GetString("Coil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp. Heat.
        /// </summary>
        public static string ComponentHeat {
            get {
                return ResourceManager.GetString("ComponentHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp. Travel Card.
        /// </summary>
        public static string ComponentOMI {
            get {
                return ResourceManager.GetString("ComponentOMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp. Part #.
        /// </summary>
        public static string ComponentPart {
            get {
                return ResourceManager.GetString("ComponentPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuation Travel Card.
        /// </summary>
        public static string ContinuationTravelCard {
            get {
                return ResourceManager.GetString("ContinuationTravelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Ideal Clamp Products, All rights reserved.
        ///This program is the confidential and proprietary intellectual property of Ideal Clamp Products. Any unauthorized use, reproduction, or preparation of derivative software represented by this program is strictly prohibited..
        /// </summary>
        public static string CopyWrite {
            get {
                return ResourceManager.GetString("CopyWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Travel Card.
        /// </summary>
        public static string CreateOMI {
            get {
                return ResourceManager.GetString("CreateOMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAFT.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup TC# DRG#.
        /// </summary>
        public static string DrawingNumber {
            get {
                return ResourceManager.GetString("DrawingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUE DATE.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gage.
        /// </summary>
        public static string Gage {
            get {
                return ResourceManager.GetString("Gage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEAT.
        /// </summary>
        public static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a previous Travel is not selected a new Travel Card will be created.
        /// </summary>
        public static string HidePreviousOMIList {
            get {
                return ResourceManager.GetString("HidePreviousOMIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Spec..
        /// </summary>
        public static string HighSpec {
            get {
                return ResourceManager.GetString("HighSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF AUDITED PLACE&lt;br /&gt; AUDIT STICKER HERE..
        /// </summary>
        public static string IfAudited {
            get {
                return ResourceManager.GetString("IfAudited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RID # IF REJECTED.
        /// </summary>
        public static string IfRejected {
            get {
                return ResourceManager.GetString("IfRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have performed and approved the final inspection and the operator manufacturing instructions..
        /// </summary>
        public static string InspectionSignOff {
            get {
                return ResourceManager.GetString("InspectionSignOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Spec..
        /// </summary>
        public static string LowSpec {
            get {
                return ResourceManager.GetString("LowSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string MeasurmentTool {
            get {
                return ResourceManager.GetString("MeasurmentTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Continuation Travel Cards.
        /// </summary>
        public static string NumberOfCards {
            get {
                return ResourceManager.GetString("NumberOfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Card.
        /// </summary>
        public static string OMI {
            get {
                return ResourceManager.GetString("OMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Card Preview.
        /// </summary>
        public static string OMIPreview {
            get {
                return ResourceManager.GetString("OMIPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Code.
        /// </summary>
        public static string OperationCode {
            get {
                return ResourceManager.GetString("OperationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PACK CODE .
        /// </summary>
        public static string PackCodeNumber {
            get {
                return ResourceManager.GetString("PackCodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PART .
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a part number.
        /// </summary>
        public static string PartNumPlease {
            get {
                return ResourceManager.GetString("PartNumPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Search.
        /// </summary>
        public static string PartSearch {
            get {
                return ResourceManager.GetString("PartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Set Up.
        /// </summary>
        public static string PartSetUp {
            get {
                return ResourceManager.GetString("PartSetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICK UP DRIVER&apos;S SIGNATURE.
        /// </summary>
        public static string PickUpDriver {
            get {
                return ResourceManager.GetString("PickUpDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.O.#.
        /// </summary>
        public static string PONum {
            get {
                return ResourceManager.GetString("PONum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print OMI.
        /// </summary>
        public static string PrintTravelCard {
            get {
                return ResourceManager.GetString("PrintTravelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAW MAT&apos;L.
        /// </summary>
        public static string RawMaterial {
            get {
                return ResourceManager.GetString("RawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done, Return to OMI Application.
        /// </summary>
        public static string ReturnToApp {
            get {
                return ResourceManager.GetString("ReturnToApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev..
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role(s).
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smple&lt;br /&gt;Sz.
        /// </summary>
        public static string SampleSz {
            get {
                return ResourceManager.GetString("SampleSz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Product ID.
        /// </summary>
        public static string SearchPartSetUps {
            get {
                return ResourceManager.GetString("SearchPartSetUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Travel Card by Item ID.
        /// </summary>
        public static string SearchTravelCardByPartNum {
            get {
                return ResourceManager.GetString("SearchTravelCardByPartNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Travel Card.
        /// </summary>
        public static string SecondOMI {
            get {
                return ResourceManager.GetString("SecondOMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Up.
        /// </summary>
        public static string SetUp {
            get {
                return ResourceManager.GetString("SetUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from recent Travel cards for this part.
        /// </summary>
        public static string ShowPreviousOMIList {
            get {
                return ResourceManager.GetString("ShowPreviousOMIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLIER.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPLIER CERTIFICATION.
        /// </summary>
        public static string SupplierCertification {
            get {
                return ResourceManager.GetString("SupplierCertification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Process Control Plan Data Sheet.
        /// </summary>
        public static string TestCriteria {
            get {
                return ResourceManager.GetString("TestCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tote #.
        /// </summary>
        public static string Tote {
            get {
                return ResourceManager.GetString("Tote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Card.
        /// </summary>
        public static string TravelCard {
            get {
                return ResourceManager.GetString("TravelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Card  User Listing.
        /// </summary>
        public static string UserListing {
            get {
                return ResourceManager.GetString("UserListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEIGHT.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
