//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miPT_Project_6.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class AspNetUserRoles
    {

        [DisplayName("User ID")]
        public string UserId { get; set; }
        [DisplayName("Role ID")]
        public string RoleId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
