//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miPT_Project_6.Models
{
    using System;

    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Measurements
    {
        [DisplayName("ID")]
        public string Id { get; set; }
        [DisplayName("Measurement ID")]
        public int MeasurementID { get; set; }
        [DisplayName("Date")]
        public System.DateTime Date { get; set; }
        [DisplayName("Client ID")]
        public int ClientID { get; set; }
        [DisplayName("Body Weight")]
        public string BodyWeight { get; set; }
        [DisplayName("Bodyfat")]
        public Nullable<double> BodyFat { get; set; }
        [DisplayName("BMR")]
        public Nullable<int> BMR { get; set; }
        [DisplayName("Metabolic Age")]
        public Nullable<int> MetabolicAge { get; set; }
        [DisplayName("Water")]
        public Nullable<double> Water { get; set; }
        [DisplayName("Visceral Fat")]
        public Nullable<int> Visceral { get; set; }
        [DisplayName("Bone Mass")]
        public Nullable<double> BoneMass { get; set; }
        [DisplayName("Lean Mass")]
        public Nullable<double> LeanMass { get; set; }
        [DisplayName("Physique Rating")]
        public Nullable<int> PhysiqueRating { get; set; }
        [DisplayName("Chest")]
        public Nullable<double> Chest { get; set; }
        [DisplayName("Waist")]
        public Nullable<double> Waist { get; set; }
        [DisplayName("Hips")]
        public Nullable<double> Hips { get; set; }
        [DisplayName("Abdomen")]
        public Nullable<double> Abdomen { get; set; }
        [DisplayName("Client Details")]
        public virtual ClientDetails ClientDetails { get; set; }
    }
}
